stages:
- name: Build
  steps:
  - runScriptConfig:
      image: jekyll/builder:3.8
      shellScript: jekyll build
  - runScriptConfig:
      image: busybox
      shellScript: whoami
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-jekyll:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
